//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogada
    {
        public int id { get; set; }
        public int jogo_id { get; set; }
        public int campo { get; set; }
        public Nullable<int> subCampo { get; set; }
        public string jogada1 { get; set; }
    
        public virtual Jogo Jogo { get; set; }
    }
}
